#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2016 OpenWrt.org

START=50
STOP=50

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/i2pd --conf=/etc/i2pd.conf --pidfile /var/run/i2pd.pid --daemon --service
	procd_close_instance
}
