#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2016 OpenWrt.org

START=50
STOP=50

USE_PROCD=1

EXTRA_COMMANDS="gracestop"
EXTRA_HELP="	gracestop Graceful shutdown. i2pd will wait for 10 minutes and stop."

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/i2pd --conf=/etc/i2pd.conf --pidfile /var/run/i2pd.pid --service
	procd_set_param file /etc/i2pd.conf
	procd_close_instance
}

gracestop() {
	kill -INT $( cat /var/run/i2pd.pid )
}
